export const GET_NOT_VERIFY_PHOTOS = "GET_NOT_VERIFY_PHOTOS";
export const GET_NOT_VERIFY_PHOTOS_FAILED = "GET_NOT_VERIFY_PHOTOS_FAILED";
export const GET_NOT_VERIFY_PHOTOS_SUCCESS = "GET_NOT_VERIFY_PHOTOS_SUCCESS";
